//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toolVanDao.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("THANHLOI")]
        public string UsernameLoginWeb {
            get {
                return ((string)(this["UsernameLoginWeb"]));
            }
            set {
                this["UsernameLoginWeb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kythuat")]
        public string PasswordLoginWeb {
            get {
                return ((string)(this["PasswordLoginWeb"]));
            }
            set {
                this["PasswordLoginWeb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01GTKT0/001")]
        public string MauSo {
            get {
                return ((string)(this["MauSo"]));
            }
            set {
                this["MauSo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VD/14P")]
        public string KyHieu {
            get {
                return ((string)(this["KyHieu"]));
            }
            set {
                this["KyHieu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HoaDonGtGt")]
        public string TableInvocie {
            get {
                return ((string)(this["TableInvocie"]));
            }
            set {
                this["TableInvocie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://0106393463.nextinvoice.vn/api/InvoiceAPI/Save")]
        public string UrlSave {
            get {
                return ((string)(this["UrlSave"]));
            }
            set {
                this["UrlSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://0106393463.nextinvoice.vn/api/Invoice/GetById?id=")]
        public string UrlGetInvoiceByInvoiceAuthId {
            get {
                return ((string)(this["UrlGetInvoiceByInvoiceAuthId"]));
            }
            set {
                this["UrlGetInvoiceByInvoiceAuthId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://0106393463.nextinvoice.vn/api/System/ExecuteCommand")]
        public string UrlCommand {
            get {
                return ((string)(this["UrlCommand"]));
            }
            set {
                this["UrlCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CM00027")]
        public string Command {
            get {
                return ((string)(this["Command"]));
            }
            set {
                this["Command"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KTMC")]
        public string svname {
            get {
                return ((string)(this["svname"]));
            }
            set {
                this["svname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Login2")]
        public string txtusername {
            get {
                return ((string)(this["txtusername"]));
            }
            set {
                this["txtusername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456")]
        public string txtpassword {
            get {
                return ((string)(this["txtpassword"]));
            }
            set {
                this["txtpassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int authen {
            get {
                return ((int)(this["authen"]));
            }
            set {
                this["authen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mau_so {
            get {
                return ((string)(this["mau_so"]));
            }
            set {
                this["mau_so"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ky_hieu {
            get {
                return ((string)(this["ky_hieu"]));
            }
            set {
                this["ky_hieu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InvoiceCodeId {
            get {
                return ((string)(this["InvoiceCodeId"]));
            }
            set {
                this["InvoiceCodeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://0106393463.nextinvoice.vn/api/System/GetDataReferencesByRefId?refId=RF001" +
            "87")]
        public string UrlRef {
            get {
                return ((string)(this["UrlRef"]));
            }
            set {
                this["UrlRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0106393463")]
        public string MST {
            get {
                return ((string)(this["MST"]));
            }
            set {
                this["MST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlSBM {
            get {
                return ((string)(this["UrlSBM"]));
            }
            set {
                this["UrlSBM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Folder {
            get {
                return ((string)(this["Folder"]));
            }
            set {
                this["Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://tracuuhoadon.nextinvoice.vn/Tracuu2/ExportZipFileXML")]
        public string UrlDownloadXML {
            get {
                return ((string)(this["UrlDownloadXML"]));
            }
            set {
                this["UrlDownloadXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlRef78 {
            get {
                return ((string)(this["UrlRef78"]));
            }
            set {
                this["UrlRef78"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlDownloadXml78 {
            get {
                return ((string)(this["UrlDownloadXml78"]));
            }
            set {
                this["UrlDownloadXml78"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlDownloadpdf78 {
            get {
                return ((string)(this["UrlDownloadpdf78"]));
            }
            set {
                this["UrlDownloadpdf78"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://4600240441002.nextinvoice.vn/api/Account/Login")]
        public string UrlLogin {
            get {
                return ((string)(this["UrlLogin"]));
            }
            set {
                this["UrlLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlDownloadPDF {
            get {
                return ((string)(this["UrlDownloadPDF"]));
            }
            set {
                this["UrlDownloadPDF"] = value;
            }
        }
    }
}
